In [ ]:
import pandas as pd

# CSV 파일 경로
file_path = r"C:\Users\SSU\Desktop\acc.csv"
data = pd.read_csv(file_path)

In [2]:
data

,acc_year,occrrnc_dt,dght_cd,occrrnc_day_cd,dth_dnv_cnt,injpsn_cnt,se_dnv_cnt,sl_dnv_cnt,wnd_dnv_cnt,occrrnc_lc_sido_cd,...,acc_ty_cd,aslt_vtr_cd,road_frm_lclas_cd,road_frm_cd,wrngdo_isrty_vhcty_lclas_cd,dmge_isrty_vhcty_lclas_cd,occrrnc_lc_x_crd,occrrnc_lc_y_crd,lo_crd,la_crd
0,2012,2012010113,1,1,1,3,1,1,0,1400,...,32,5,01,05,3,##,1118120,1964153,128.839343,37.669304
1,2012,2012012519,2,4,1,2,0,1,0,1400,...,Z2,5,01,05,1,03,1125263,1971795,128.921634,37.737212
2,2012,2012031023,2,7,1,4,0,3,0,1400,...,21,2,01,05,1,01,1116396,1987118,128.823489,37.876455
3,2012,2012032205,2,5,1,1,0,0,0,1400,...,01,7,01,Z1,3,12,1121928,1975240,128.884373,37.768704
4,2012,2012041313,1,6,1,1,0,0,0,1400,...,22,3,02,06,5,02,1123471,1974147,128.901702,37.758648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242,2023,2023111518,2,4,2,2,0,0,0,1400,...,01,7,02,07,1,12,1055969,1935085,128.132470,37.413207
2243,2023,2023111822,2,7,1,1,0,0,0,1400,...,34,5,01,05,1,##,1059100,1943458,128.168566,37.488497
2244,2023,2023112011,1,2,1,1,0,0,0,1400,...,22,5,01,05,3,08,1049264,1944165,128.057311,37.495429
2245,2023,2023121715,1,1,1,1,0,0,0,1400,...,34,5,01,05,1,##,1034189,1947168,127.886451,37.523071
2246,2023,2023122617,1,3,1,1,0,0,0,1400,...,01,5,01,05,1,12,1044330,1943148,128.001435,37.486512

In [3]:
# 전체 결측값 개수 확인
print("컬럼별 결측값 개수:")
print(data.isnull().sum())

컬럼별 결측값 개수:
acc_year                       0
occrrnc_dt                     0
dght_cd                        0
occrrnc_day_cd                 0
dth_dnv_cnt                    0
injpsn_cnt                     0
se_dnv_cnt                     0
sl_dnv_cnt                     0
wnd_dnv_cnt                    0
occrrnc_lc_sido_cd             0
occrrnc_lc_sgg_cd              0
acc_ty_lclas_cd                0
acc_ty_mlsfc_cd                0
acc_ty_cd                      0
aslt_vtr_cd                    0
road_frm_lclas_cd              0
road_frm_cd                    0
wrngdo_isrty_vhcty_lclas_cd    0
dmge_isrty_vhcty_lclas_cd      0
occrrnc_lc_x_crd               0
occrrnc_lc_y_crd               0
lo_crd                         0
la_crd                         0
dtype: int64

In [4]:
# 기존 열 이름 리스트
original_columns = [
    'acc_year', 'occrrnc_dt', 'dght_cd', 'occrrnc_day_cd', 
    'dth_dnv_cnt', 'injpsn_cnt', 'se_dnv_cnt', 'sl_dnv_cnt', 
    'wnd_dnv_cnt', 'occrrnc_lc_sido_cd', 'occrrnc_lc_sgg_cd', 
    'acc_ty_lclas_cd', 'acc_ty_mlsfc_cd', 'acc_ty_cd', 'aslt_vtr_cd', 
    'road_frm_lclas_cd', 'road_frm_cd', 'wrngdo_isrty_vhcty_lclas_cd', 
    'dmge_isrty_vhcty_lclas_cd', 'occrrnc_ls_x_crd', 'occrrnc_ls_y_crd', 
    'lo_crd', 'la_crd'
]

# 변경할 열 이름 리스트
new_columns = [
    '사고년도', '월일시', '주야구분코드', '요일코드', '사망자수', '부상자수', 
    '중상자수', '경상자수', '부상신고자수', '위치 시도코드', '위치 시군구코드', 
    '사고유형 대분류코드', '사고유형 중분류코드', '사고유형 코드', 
    '가해자 법규위반코드', '도로형태 대분류코드', '도로형태 코드', 
    '가해당사자 차종별대분류코드', '피해당사자 차종별대분류코드', 
    '위치 X좌표', '위치 Y좌표', '경도좌표', '위도좌표'
]

# 열 이름 변경
data.columns = new_columns

# 결과 확인
print("열 이름 변경 완료:")
print(data.columns)

열 이름 변경 완료:
Index(['사고년도', '월일시', '주야구분코드', '요일코드', '사망자수', '부상자수', '중상자수', '경상자수',
       '부상신고자수', '위치 시도코드', '위치 시군구코드', '사고유형 대분류코드', '사고유형 중분류코드', '사고유형 코드',
       '가해자 법규위반코드', '도로형태 대분류코드', '도로형태 코드', '가해당사자 차종별대분류코드',
       '피해당사자 차종별대분류코드', '위치 X좌표', '위치 Y좌표', '경도좌표', '위도좌표'],
      dtype='object')

In [5]:
data.head()

,사고년도,월일시,주야구분코드,요일코드,사망자수,부상자수,중상자수,경상자수,부상신고자수,위치 시도코드,...,사고유형 코드,가해자 법규위반코드,도로형태 대분류코드,도로형태 코드,가해당사자 차종별대분류코드,피해당사자 차종별대분류코드,위치 X좌표,위치 Y좌표,경도좌표,위도좌표
0,2012,2012010113,1,1,1,3,1,1,0,1400,...,32,5,01,05,3,##,1118120,1964153,128.839343,37.669304
1,2012,2012012519,2,4,1,2,0,1,0,1400,...,Z2,5,01,05,1,03,1125263,1971795,128.921634,37.737212
2,2012,2012031023,2,7,1,4,0,3,0,1400,...,21,2,01,05,1,01,1116396,1987118,128.823489,37.876455
3,2012,2012032205,2,5,1,1,0,0,0,1400,...,01,7,01,Z1,3,12,1121928,1975240,128.884373,37.768704
4,2012,2012041313,1,6,1,1,0,0,0,1400,...,22,3,02,06,5,02,1123471,1974147,128.901702,37.758648

In [6]:
data.shape

(2247, 23)

In [7]:
# 삭제할 열 이름 리스트
columns_to_drop = ['월일시','위치 X좌표', '위치 Y좌표', '경도좌표', '위도좌표']

# 열 삭제
data = data.drop(columns=columns_to_drop)

# 결과 확인
print("열 삭제 후 데이터프레임:")
print(data.head())

열 삭제 후 데이터프레임:
   사고년도  주야구분코드  요일코드  사망자수  부상자수  중상자수  경상자수  부상신고자수  위치 시도코드  위치 시군구코드  \
0  2012       1     1     1     3     1     1       0     1400      1404
1  2012       2     4     1     2     0     1       0     1400      1404
2  2012       2     7     1     4     0     3       0     1400      1404
3  2012       2     5     1     1     0     0       0     1400      1404
4  2012       1     6     1     1     0     0       0     1400      1404

   사고유형 대분류코드  사고유형 중분류코드 사고유형 코드  가해자 법규위반코드 도로형태 대분류코드 도로형태 코드  \
0           3          31      32           5         01      05
1           2          23      Z2           5         01      05
2           2          21      21           2         01      05
3           1          11      01           7         01      Z1
4           2          22      22           3         02      06

   가해당사자 차종별대분류코드 피해당사자 차종별대분류코드
0               3             ##
1               1             03
2               1             01
3               3             12
4               5             02

In [9]:
# 중상자수 컬럼 통계 출력
print("중상자수 통계 정보:")
print(data['중상자수'].describe()) # 최대 25명, 평균 0.3명, 최소 0명

중상자수 통계 정보:
count    2247.000000
mean        0.340899
std         1.033472
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        25.000000
Name: 중상자수, dtype: float64

In [11]:
# 중상자수 컬럼 통계 출력
print("경상자수  통계 정보:")
print(data['경상자수'].describe())  # 최대 33명, 평균 0.3명, 최소 0명

경상자수  통계 정보:
count    2247.000000
mean        0.303071
std         1.401661
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        33.000000
Name: 경상자수, dtype: float64

In [12]:
# 중상자수 컬럼 통계 출력
print("사망자수  통계 정보:")
print(data['사망자수'].describe()) # 평균 1명, 최소 1명, 최대 1명

사망자수  통계 정보:
count    2247.000000
mean        1.056965
std         0.313476
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         5.000000
Name: 사망자수, dtype: float64

In [13]:
# 사고 피해 정도 열 생성 
# 사고 피해 정도 계산
data['사고 피해 정도'] = (data['사망자수'] * 10) + (data['중상자수'] * 5) + (data['경상자수'] * 1)

# 결과 확인
print(data[['사망자수', '중상자수', '경상자수', '사고 피해 정도']].head())

   사망자수  중상자수  경상자수  사고 피해 정도
0     1     1     1        16
1     1     0     1        11
2     1     0     3        13
3     1     0     0        10
4     1     0     0        10

In [14]:
# 중상자수 컬럼 통계 출력
print("사고 피해 정도 통계 정보:")
print(data['사고 피해 정도'].describe()) # 평균 1명, 최소 1명, 최대 1명

사고 피해 정도 통계 정보:
count    2247.000000
mean       12.577214
std         7.559922
min        10.000000
25%        10.000000
50%        10.000000
75%        11.000000
max       172.000000
Name: 사고 피해 정도, dtype: float64

In [15]:
data.columns

Index(['사고년도', '주야구분코드', '요일코드', '사망자수', '부상자수', '중상자수', '경상자수', '부상신고자수',
       '위치 시도코드', '위치 시군구코드', '사고유형 대분류코드', '사고유형 중분류코드', '사고유형 코드',
       '가해자 법규위반코드', '도로형태 대분류코드', '도로형태 코드', '가해당사자 차종별대분류코드',
       '피해당사자 차종별대분류코드', '사고 피해 정도'],
      dtype='object')

In [16]:
data.head()

,사고년도,주야구분코드,요일코드,사망자수,부상자수,중상자수,경상자수,부상신고자수,위치 시도코드,위치 시군구코드,사고유형 대분류코드,사고유형 중분류코드,사고유형 코드,가해자 법규위반코드,도로형태 대분류코드,도로형태 코드,가해당사자 차종별대분류코드,피해당사자 차종별대분류코드,사고 피해 정도
0,2012,1,1,1,3,1,1,0,1400,1404,3,31,32,5,01,05,3,##,16
1,2012,2,4,1,2,0,1,0,1400,1404,2,23,Z2,5,01,05,1,03,11
2,2012,2,7,1,4,0,3,0,1400,1404,2,21,21,2,01,05,1,01,13
3,2012,2,5,1,1,0,0,0,1400,1404,1,11,01,7,01,Z1,3,12,10
4,2012,1,6,1,1,0,0,0,1400,1404,2,22,22,3,02,06,5,02,10

## 로지스틱 회귀 - 사고 피해 정도

In [36]:
# 증강으로 '높음'의 균형을 어느정도 맞추었지만 정확도 낮아짐 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import LabelEncoder

# '사고 피해 정도'를 범주형으로 변환
def categorize_damage(severity):
    if severity < 10:
        return '낮음'
    elif severity < 20:
        return '중간'
    else:
        return '높음'

# 데이터 전처리
data['피해_범주'] = data['사고 피해 정도'].apply(categorize_damage)

# 입력 변수(X)와 출력 변수(y) 설정
X = data[['주야구분코드', '요일코드', '위치 시도코드', '위치 시군구코드', '사고유형 코드',
          '가해자 법규위반코드', '도로형태 코드', 
          '가해당사자 차종별대분류코드', '피해당사자 차종별대분류코드']]

# 범주형 변수를 숫자로 변환 (One-Hot Encoding)
X = pd.get_dummies(X, columns=X.columns)

# 모든 값이 숫자형인지 확인 및 변환
X = X.astype(float)  # 불리언 값이 포함된 경우 숫자형으로 변환

# 출력 변수 설정
y = data['피해_범주']

# 학습용 데이터와 테스트용 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# y_train을 정수형으로 변환
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)

# SMOTE를 사용한 오버샘플링
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train_encoded)

# 로지스틱 회귀 모델 학습
model = LogisticRegression(max_iter=1000)
model.fit(X_train_resampled, y_train_resampled)

# 예측 및 평가
y_pred = model.predict(X_test)

# 예측 결과를 범주형으로 복원
y_pred_labels = label_encoder.inverse_transform(y_pred)
y_test_labels = y_test.values  # 테스트 데이터는 원래 범주형 값

# 평가 결과 출력
print("정확도:", accuracy_score(y_test_labels, y_pred_labels))
print("분류 리포트:\n", classification_report(y_test_labels, y_pred_labels))

정확도: 0.7666666666666667
분류 리포트:
               precision    recall  f1-score   support

          높음       0.29      0.79      0.42        48
          중간       0.97      0.76      0.85       402

    accuracy                           0.77       450
   macro avg       0.63      0.78      0.64       450
weighted avg       0.90      0.77      0.81       450

In [21]:
pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Downloading imbalanced_learn-0.12.4-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: numpy>=1.17.3 in c:\users\ssu\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imbalanced-learn->imblearn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\ssu\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imbalanced-learn->imblearn) (1.14.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\ssu\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imbalanced-learn->imblearn) (1.5.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\ssu\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imbalanced-learn->imblearn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ssu\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imbalanced-learn->imblearn) (3.5.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Downloading imbalanced_learn-0.12.4-py3-none-any.whl (258 kB)
Installing collected packages: imbalanced-learn, imblearn
Successfully installed imbalanced-learn-0.12.4 imblearn-0.0
Note: you may need to restart the kernel to use updated packages.

### XGBoost

In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score

# 데이터 전처리: 사고 피해 정도를 범주형으로 변환
def categorize_damage(severity):
    if severity <= 10:
        return '낮음'
    elif severity <= 20:
        return '중간'
    else:
        return '높음'

# '사고 피해 정도' 범주화
data['피해_범주'] = data['사고 피해 정도'].apply(categorize_damage)

# 입력 변수와 출력 변수 설정
X = data[['주야구분코드', '요일코드', '위치 시도코드', '위치 시군구코드', 
          '사고유형 대분류코드', '사고유형 중분류코드', '사고유형 코드',
          '가해자 법규위반코드', '도로형태 대분류코드', '도로형태 코드', 
          '가해당사자 차종별대분류코드', '피해당사자 차종별대분류코드']]
y = data['피해_범주']

# 범주형 변수 One-Hot Encoding
X = pd.get_dummies(X, columns=X.columns)

# 목표 변수(Label) 숫자형 변환
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)  # '낮음', '중간', '높음' -> 0, 1, 2

# 데이터 타입 확인 및 변환
X = X.astype(float)

# 학습 데이터와 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# SMOTE를 이용한 오버샘플링
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# 데이터 정규화 (StandardScaler)
scaler = StandardScaler()
X_train_resampled_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

# XGBoost 모델 학습
xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train_resampled_scaled, y_train_resampled)

# 예측 및 평가
y_pred = xgb_model.predict(X_test_scaled)

# 목표 변수 복원 (숫자 -> 범주형)
y_pred_labels = label_encoder.inverse_transform(y_pred)
y_test_labels = label_encoder.inverse_transform(y_test)

# 평가 결과 출력
print("정확도:", accuracy_score(y_test_labels, y_pred_labels))
print("분류 리포트:\n", classification_report(y_test_labels, y_pred_labels))

C:\Users\SSU\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\xgboost\core.py:158: UserWarning: [03:50:27] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0ed59c031377d09b8-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

정확도: 0.7444444444444445
분류 리포트:
               precision    recall  f1-score   support

          낮음       0.84      0.89      0.86       319
          높음       0.24      0.13      0.17        31
          중간       0.51      0.47      0.49       100

    accuracy                           0.74       450
   macro avg       0.53      0.50      0.51       450
weighted avg       0.72      0.74      0.73       450

In [37]:
## SMOTE 했는데 성능차이 없음
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score

# '사고 피해 정도'를 범주형으로 변환하는 함수
def categorize_damage(severity):
    if severity <= 10:
        return '낮음'
    elif severity <= 20:
        return '중간'
    else:
        return '높음'

# 데이터 로드 (예시: data가 이미 로드되어 있다고 가정)
# data = pd.read_csv('data.csv')

# '사고 피해 정도'를 범주화
data['피해_범주'] = data['사고 피해 정도'].apply(categorize_damage)

# 입력 변수와 출력 변수 설정
X = data[['주야구분코드', '요일코드', '위치 시도코드', '위치 시군구코드', 
          '사고유형 대분류코드', '사고유형 중분류코드', '사고유형 코드',
          '가해자 법규위반코드', '도로형태 대분류코드', '도로형태 코드', 
          '가해당사자 차종별대분류코드', '피해당사자 차종별대분류코드']]
y = data['피해_범주']

# 범주형 변수를 One-Hot Encoding으로 변환
X = pd.get_dummies(X, columns=X.columns)

# 목표 변수(Label) 숫자형 변환
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)  # '낮음', '중간', '높음' -> 0, 1, 2

# 입력 데이터 타입 변환 (SMOTE 및 모델 호환성을 위해 float 타입으로 변환)
X = X.astype(float)

# 학습 데이터와 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# SMOTE를 이용한 오버샘플링
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# 데이터 정규화 (StandardScaler)
scaler = StandardScaler()
X_train_resampled_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

# XGBoost 모델 학습
xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train_resampled_scaled, y_train_resampled)

# 예측
y_pred = xgb_model.predict(X_test_scaled)

# 목표 변수 복원 (숫자 -> 범주형)
y_pred_labels = label_encoder.inverse_transform(y_pred)
y_test_labels = label_encoder.inverse_transform(y_test)

# 평가 결과 출력
print("정확도:", accuracy_score(y_test_labels, y_pred_labels))
print("분류 리포트:\n", classification_report(y_test_labels, y_pred_labels))

C:\Users\SSU\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\xgboost\core.py:158: UserWarning: [04:03:18] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0ed59c031377d09b8-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

정확도: 0.7444444444444445
분류 리포트:
               precision    recall  f1-score   support

          낮음       0.84      0.89      0.86       319
          높음       0.24      0.13      0.17        31
          중간       0.51      0.47      0.49       100

    accuracy                           0.74       450
   macro avg       0.53      0.50      0.51       450
weighted avg       0.72      0.74      0.73       450

### 1. Random Forest / 2. Gradient Boosting / 3. LightGBM / 4. CatBoost 성능 비교 -> model.py

### 로지스틱 + XGBoost 앙상블
- 성능 개선 X

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score

# '사고 피해 정도'를 범주형으로 변환
def categorize_damage(severity):
    if severity <= 10:
        return '낮음'
    elif severity <= 20:
        return '중간'
    else:
        return '높음'

# 데이터 로드 및 전처리
# 예시: data를 이미 로드했다고 가정
data['피해_범주'] = data['사고 피해 정도'].apply(categorize_damage)

# 입력 변수와 출력 변수 설정
X = data[['주야구분코드', '요일코드', '위치 시도코드', '위치 시군구코드', 
          '사고유형 코드', '가해자 법규위반코드', '도로형태 코드', 
          '가해당사자 차종별대분류코드', '피해당사자 차종별대분류코드']]
y = data['피해_범주']

# 범주형 변수를 One-Hot Encoding
X = pd.get_dummies(X, columns=X.columns)
X = X.astype(float)

# 출력 변수(Label) 숫자형 변환
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)  # '낮음', '중간', '높음' -> 0, 1, 2

# 학습 데이터와 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# SMOTE를 사용한 오버샘플링
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# 데이터 정규화 (StandardScaler)
scaler = StandardScaler()
X_train_resampled_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

# 1. Logistic Regression 모델 학습
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_resampled, y_train_resampled)
logistic_probs = logistic_model.predict_proba(X_test_scaled)

# 2. XGBoost 모델 학습
xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train_resampled_scaled, y_train_resampled)
xgb_probs = xgb_model.predict_proba(X_test_scaled)

# 앙상블 - Soft Voting (평균 확률 계산)
ensemble_probs = (logistic_probs + xgb_probs) / 2
ensemble_preds = ensemble_probs.argmax(axis=1)

# 목표 변수 복원 (숫자 -> 범주형)
ensemble_labels = label_encoder.inverse_transform(ensemble_preds)
y_test_labels = label_encoder.inverse_transform(y_test)

# 평가 결과 출력
print("앙상블 정확도:", accuracy_score(y_test_labels, ensemble_labels))
print("앙상블 분류 리포트:\n", classification_report(y_test_labels, ensemble_labels))

C:\Users\SSU\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\SSU\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\xgboost\core.py:158: UserWarning: [04:05:33] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0ed59c031377d09b8-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

앙상블 정확도: 0.6555555555555556
앙상블 분류 리포트:
               precision    recall  f1-score   support

          낮음       0.83      0.77      0.80       319
          높음       0.22      0.45      0.29        31
          중간       0.39      0.34      0.36       100

    accuracy                           0.66       450
   macro avg       0.48      0.52      0.49       450
weighted avg       0.69      0.66      0.67       450